export class GlobalData {
    static $_user_level_max;
    static $_user_default_headurl;
    static $_global_language_str = null;
    static $_global_dataProfile_txt = null;
    static $_globalMaskSprite = null;
    static $_global_mixtrue_gem = 500;
    static $_global_gold_remind = 5000;
    static $_global_population_remind = 1.5;
    static $_global_speedup_level = 0;
    static $_wolfAtt_Obj;
    static $_towerAtt_Obj;
    static $_normal_towerAtt_Obj;
    static $_wallAtt_Obj;
    static $_normal_wallAtt_Obj;
    static $_barrierAtt_Obj;
    static $_bulletAtt_Obj;
    static $_bombAtt_Obj;
    static $_roadblockAtt_Obj;
    static $_exchange_properties;
    static $_exchange_all = [];
    static $_exchange_now = [];
    static $_skillAtt_Obj;
    static $_skillPackage_Obj;
    static $_map_Obj;
    static $_wave_hard_Obj;
    static $_task_Obj;
    static $_level_up_gift;
    static $_pass_map_gift;
    static $_tower_worth_factor;
    static $_wolf_worth_factor;
    static $_defend_map_snarp_max;
    static $_defend_succ_factor;
    static $_defend_failed_factor;
    static $_defend_arena_succ_factor;
    static $_defend_arena_failed_factor;
    static $_conflict_skill_kind;
    static $_skill_lvup_spend;
    static $_skill_grade_score;
    static $_global_properties;
    static $_camp_wolf_lv_max;

    static umapsById;
};
